@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.gems.world.placement;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;