modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${issue_tracker_url}"
displayURL="${display_url}"
#logoFile="logo.png"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
#updateJSONURL="https://raw.githubusercontent.com/SilentChaos512/SilentLib/1.20.x/update.json"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="silentgear"
type="optional"
versionRange="${silentgear_version_range}"
ordering="NONE"
side="BOTH"
