modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/SilentChaos512/SilentGems/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/silents-gems"
#logoFile="examplemod.png" #optional
credits=""
authors="SilentChaos512"

[[mods]]
    modId="silentgems"
    version="${file.jarVersion}"
    displayName="Silent's Gems: Base"
    updateJSONURL="https://raw.githubusercontent.com/SilentChaos512/SilentGems/1.18.x/update.json"
    description='''
    Downloads: https://www.curseforge.com/minecraft/mc-mods/silents-gems (I do not upload anywhere else)
    Changelog: https://github.com/SilentChaos512/SilentGems/blob/1.18.x/CHANGELOG.md
    Source: https://github.com/SilentChaos512/SilentGems/
    Issues: https://github.com/SilentChaos512/SilentGems/issues
    '''

[[dependencies.silentgems]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.silentgems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.silentgems]]
    modId="silentlib"
    mandatory=true
    versionRange="[6.2,7)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.silentgems]]
    modId="silentgear"
    mandatory=false
    versionRange="[2.10,)"
    ordering="AFTER"
    side="BOTH"
