@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.gems.block.teleporter;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;