@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.gemschaos.chaos;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;