@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.gems.potion;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;